### ISSUE TITLE
Minimum Python version

### ISSUE THREAD

**Issue by hasindu2008** [comprna/radian#2]
I am trying to install radian on my laptop with Python 3.7 and I am getting an issue that ``Ignored the following versions that require a different python version: 3.6.0 Requires-Python >=3.8; 3.6.0rc1 Requires-Python >=3.8; 3.6.0rc2 Requires-Python >=3.8; 3.6.1 Requires-Python >=3.8`. Is it possible that this matplotlib version be downgraded?

**Comment by a-sneddon** [comment]
Hi Hasindu,

The matplotlib version can be downgraded - it is only used for visualisation during debugging, so you can use a version compatible with 3.7 without affecting the basecalling.

Thanks,
